function [T] = kinetic_hand(MT, MMT, MR, MR2, JT, A, B, dx, dy, phi, dphi, theta, dtheta, psi)

fP = dx^2+dy^2;
fM = 2*dx*dphi*(-B*sin(phi) - A*cos(phi)) + 2*dy*dphi*(B*cos(phi) - A*sin(phi))...
    + dphi^2*(B.^2+A.^2);
fMsum = sum(fM);
fi1 = 2*dx.*dtheta.*cos(theta).*cos(psi+phi)...
    - 2*dx.*dphi.*sin(theta).*sin(psi+phi)...
    + 2*dy.*dtheta.*cos(theta).*sin(psi+phi)...
    + 2*dy.*dphi.*sin(theta).*cos(psi+phi)...
    + 2*dphi.*dtheta.*B.*sin(psi).*cos(theta)...
    + 2*dphi.^2.*B.*cos(psi).*sin(theta)...
    - 2*dphi.*dtheta.*A.*cos(psi).*cos(theta)...
    + 2*dphi.^2.*A.*sin(psi).*sin(theta);
fi1sum = sum(fi1);
fi2 = dphi.^2.*sin(theta).^2 + dtheta.^2;
fi2sum = sum(fi2);

T = 0.5*(MT*fP + MMT*fMsum + MR*fi1sum + MR2*fi2sum + JT*dphi^2);


end