function M = mphi_2_mass(t,in2,in3,in4)
%MPHI_2_MASS
%    M = MPHI_2_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:46

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
R2 = in4(2,:);
gamma1 = in4(3,:);
gamma2 = in4(4,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(5,:);
psi2 = in4(6,:);
theta1 = in2(2,:);
theta2 = in2(3,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = lb.^2;
t5 = mb.*t4;
t6 = lp.^2;
t7 = mp.*t6;
t8 = t5+t7;
t9 = mM+mb+mp;
t10 = lb.*mb.*2.0;
t11 = t10-lp.*mp.*2.0;
t12 = gamma1-psi1;
t13 = gamma2-psi2;
t14 = lb.*mb;
t18 = lp.*mp;
t15 = t14-t18;
t16 = sin(t12);
t17 = cos(theta1);
t19 = sin(t13);
t20 = cos(theta2);
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,JM33.*2.0+JP33+R1.^2.*t9+R2.^2.*t9+t2.^2.*t8+t3.^2.*t8+R1.*t2.*t11.*cos(t12)+R2.*t3.*t11.*cos(t13),-R1.*t15.*t16.*t17,-R2.*t15.*t19.*t20,0.0,0.0,0.0,-R1.*t15.*t16.*t17,t8,0.0,0.0,0.0,0.0,-R2.*t15.*t19.*t20,0.0,t8],[6,6]);
