function dxdt = mphi_1_row(t,in2,in3,in4,in5)
%MPHI_1_ROW
%    DXDT = MPHI_1_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:27

R1 = in4(1,:);
Uphi = in5(1,:);
Utheta1 = in5(2,:);
ct = in3(13,:);
d = in3(6,:);
dphi = in2(3,:);
dtheta1 = in2(4,:);
g = in3(5,:);
gamma1 = in4(2,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(1,:);
psi1 = in4(3,:);
theta1 = in2(2,:);
t2 = gamma1-psi1;
t3 = cos(theta1);
t4 = sin(theta1);
t5 = lb.*mb;
t11 = lp.*mp;
t6 = t5-t11;
t7 = lb.^2;
t8 = lp.^2;
t9 = dphi.^2;
t10 = cos(t2);
dxdt = [dphi;dtheta1;Uphi-ct.*dphi-kt.*phi-t6.*(R1.*dtheta1.^2.*t4.*sin(t2)+R1.*dphi.*dtheta1.*t3.*t10.*2.0)-dphi.*dtheta1.*t3.*t4.*(mb.*t7.*2.0+mp.*t8.*2.0);Utheta1-d.*dtheta1+g.*t4.*t6+t3.*t4.*t9.*(mb.*t7+mp.*t8)+R1.*t3.*t6.*t9.*t10];
