function H = mphi_3_ham(t,in2,in3,in4)
%MPHI_3_HAM
%    H = MPHI_3_HAM(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 14:00:11

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
R2 = in4(2,:);
R3 = in4(3,:);
dphi = in2(5,:);
dtheta1 = in2(6,:);
dtheta2 = in2(7,:);
dtheta3 = in2(8,:);
g = in3(5,:);
gamma1 = in4(4,:);
gamma2 = in4(5,:);
gamma3 = in4(6,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(1,:);
psi1 = in4(7,:);
psi2 = in4(8,:);
psi3 = in4(9,:);
theta1 = in2(2,:);
theta2 = in2(3,:);
theta3 = in2(4,:);
t2 = dphi.^2;
t3 = cos(gamma1);
t4 = R1.^2;
t5 = sin(gamma1);
t6 = cos(gamma2);
t7 = R2.^2;
t8 = sin(gamma2);
t9 = cos(gamma3);
t10 = R3.^2;
t11 = sin(gamma3);
t12 = sin(theta1);
t13 = sin(theta2);
t14 = sin(theta3);
t15 = sin(psi1);
t16 = cos(psi1);
t17 = cos(theta1);
t18 = sin(psi2);
t19 = cos(psi2);
t20 = cos(theta2);
t21 = sin(psi3);
t22 = cos(psi3);
t23 = cos(theta3);
t24 = lb.*mb;
t25 = t24-lp.*mp;
H = t2.*(JM33.*3.0+JP33).*(1.0./2.0)+t25.*(R1.*t2.*t3.*t12.*t16.*2.0+R1.*t2.*t5.*t12.*t15.*2.0+R2.*t2.*t6.*t13.*t19.*2.0+R2.*t2.*t8.*t13.*t18.*2.0+R3.*t2.*t9.*t14.*t22.*2.0+R3.*t2.*t11.*t14.*t21.*2.0+R1.*dphi.*dtheta1.*t3.*t15.*t17.*2.0-R1.*dphi.*dtheta1.*t5.*t16.*t17.*2.0+R2.*dphi.*dtheta2.*t6.*t18.*t20.*2.0-R2.*dphi.*dtheta2.*t8.*t19.*t20.*2.0+R3.*dphi.*dtheta3.*t9.*t21.*t23.*2.0-R3.*dphi.*dtheta3.*t11.*t22.*t23.*2.0).*(1.0./2.0)+(lb.^2.*mb+lp.^2.*mp).*(t2.*t12.^2+t2.*t13.^2+t2.*t14.^2+dtheta1.^2+dtheta2.^2+dtheta3.^2).*(1.0./2.0)+kt.*phi.^2.*(1.0./2.0)+(mM+mb+mp).*(t2.*(t3.^2.*t4+t4.*t5.^2)+t2.*(t6.^2.*t7+t7.*t8.^2)+t2.*(t9.^2.*t10+t10.*t11.^2)).*(1.0./2.0)+g.*t25.*(t17+t20+t23);
