function dxdt = mx_1_row(t,in2,in3,in4,in5)
%MX_1_ROW
%    DXDT = MX_1_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:37

Utheta1 = in5(2,:);
Ux = in5(1,:);
c = in3(12,:);
d = in3(6,:);
dtheta1 = in2(4,:);
dx = in2(3,:);
g = in3(5,:);
k = in3(9,:);
lb = in3(4,:);
lp = in3(3,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(3,:);
theta1 = in2(2,:);
x = in2(1,:);
t2 = sin(theta1);
t3 = lb.*mb;
t4 = t3-lp.*mp;
dxdt = [dx;dtheta1;Ux-c.*dx-k.*x+dtheta1.^2.*t2.*t4.*cos(psi1);Utheta1-d.*dtheta1+g.*t2.*t4];
