function M = mxy_1_mass(t,in2,in3,in4)
%MXY_1_MASS
%    M = MXY_1_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:29

lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(3,:);
theta1 = in2(3,:);
t2 = mM+mP+mb+mp;
t3 = cos(theta1);
t4 = lb.*mb;
t7 = lp.*mp;
t5 = t4-t7;
t6 = cos(psi1);
t8 = t3.*t5.*t6;
t9 = sin(psi1);
t10 = t3.*t5.*t9;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,t2,0.0,t8,0.0,0.0,0.0,0.0,t2,t10,0.0,0.0,0.0,t8,t10,lb.^2.*mb+lp.^2.*mp],[6,6]);
