function dxdt = mxy_2_row(t,in2,in3,in4,in5)
%MXY_2_ROW
%    DXDT = MXY_2_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:50

Utheta1 = in5(3,:);
Utheta2 = in5(4,:);
Ux = in5(1,:);
Uy = in5(2,:);
c = in3(12,:);
d = in3(6,:);
dtheta1 = in2(7,:);
dtheta2 = in2(8,:);
dx = in2(5,:);
dy = in2(6,:);
g = in3(5,:);
k = in3(9,:);
lb = in3(4,:);
lp = in3(3,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(5,:);
psi2 = in4(6,:);
theta1 = in2(3,:);
theta2 = in2(4,:);
x = in2(1,:);
y = in2(2,:);
t2 = dtheta1.^2;
t3 = sin(theta1);
t4 = dtheta2.^2;
t5 = sin(theta2);
t6 = lb.*mb;
t8 = lp.*mp;
t7 = t6-t8;
dxdt = [dx;dy;dtheta1;dtheta2;Ux-c.*dx-k.*x+t7.*(t2.*t3.*cos(psi1)+t4.*t5.*cos(psi2));Uy-c.*dy-k.*y+t7.*(t2.*t3.*sin(psi1)+t4.*t5.*sin(psi2));Utheta1-d.*dtheta1+g.*t3.*t7;Utheta2-d.*dtheta2+g.*t5.*t7];
