function H = my_3_ham(t,in2,in3,in4)
%MY_3_HAM
%    H = MY_3_HAM(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 14:00:29

dtheta1 = in2(6,:);
dtheta2 = in2(7,:);
dtheta3 = in2(8,:);
dy = in2(5,:);
g = in3(5,:);
k = in3(9,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(7,:);
psi2 = in4(8,:);
psi3 = in4(9,:);
theta1 = in2(2,:);
theta2 = in2(3,:);
theta3 = in2(4,:);
y = in2(1,:);
t2 = lb.*mb;
t3 = t2-lp.*mp;
t4 = cos(theta1);
t5 = cos(theta2);
t6 = cos(theta3);
H = dy.^2.*(mM.*3.0+mP+mb.*3.0+mp.*3.0).*(1.0./2.0)+(lb.^2.*mb+lp.^2.*mp).*(dtheta1.^2+dtheta2.^2+dtheta3.^2).*(1.0./2.0)+k.*y.^2.*(1.0./2.0)+t3.*(dtheta1.*dy.*t4.*sin(psi1).*2.0+dtheta2.*dy.*t5.*sin(psi2).*2.0+dtheta3.*dy.*t6.*sin(psi3).*2.0).*(1.0./2.0)+g.*t3.*(t4+t5+t6);
