function dxdt = mphi_3_row(t,in2,in3,in4,in5)
%MPHI_3_ROW
%    DXDT = MPHI_3_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 14:00:10

R1 = in4(1,:);
R2 = in4(2,:);
R3 = in4(3,:);
Uphi = in5(1,:);
Utheta1 = in5(2,:);
Utheta2 = in5(3,:);
Utheta3 = in5(4,:);
ct = in3(13,:);
d = in3(6,:);
dphi = in2(5,:);
dtheta1 = in2(6,:);
dtheta2 = in2(7,:);
dtheta3 = in2(8,:);
g = in3(5,:);
gamma1 = in4(4,:);
gamma2 = in4(5,:);
gamma3 = in4(6,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(1,:);
psi1 = in4(7,:);
psi2 = in4(8,:);
psi3 = in4(9,:);
theta1 = in2(2,:);
theta2 = in2(3,:);
theta3 = in2(4,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = sin(theta3);
t5 = cos(theta1);
t6 = gamma1-psi1;
t7 = cos(theta2);
t8 = gamma2-psi2;
t9 = cos(theta3);
t10 = gamma3-psi3;
t11 = lb.*mb;
t17 = lp.*mp;
t12 = t11-t17;
t13 = lb.^2;
t14 = lp.^2;
t15 = dphi.^2;
t16 = cos(t6);
t18 = mb.*t13;
t19 = mp.*t14;
t20 = t18+t19;
t21 = cos(t8);
t22 = cos(t10);
dxdt = [dphi;dtheta1;dtheta2;dtheta3;Uphi-ct.*dphi-kt.*phi-t12.*(R1.*dtheta1.^2.*t2.*sin(t6)+R2.*dtheta2.^2.*t3.*sin(t8)+R3.*dtheta3.^2.*t4.*sin(t10)+R1.*dphi.*dtheta1.*t5.*t16.*2.0+R2.*dphi.*dtheta2.*t7.*t21.*2.0+R3.*dphi.*dtheta3.*t9.*t22.*2.0)-(mb.*t13.*2.0+mp.*t14.*2.0).*(dphi.*dtheta1.*t2.*t5+dphi.*dtheta2.*t3.*t7+dphi.*dtheta3.*t4.*t9);Utheta1-d.*dtheta1+g.*t2.*t12+t2.*t5.*t15.*t20+R1.*t5.*t12.*t15.*t16;Utheta2-d.*dtheta2+g.*t3.*t12+t3.*t7.*t15.*t20+R2.*t7.*t12.*t15.*t21;Utheta3-d.*dtheta3+g.*t4.*t12+t4.*t9.*t15.*t20+R3.*t9.*t12.*t15.*t22];
