function M = mphi_1_mass(t,in2,in3,in4)
%MPHI_1_MASS
%    M = MPHI_1_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:27

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
gamma1 = in4(2,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(3,:);
theta1 = in2(2,:);
t2 = sin(theta1);
t3 = gamma1-psi1;
t4 = sin(t3);
t5 = cos(theta1);
t6 = lb.*mb;
t7 = t6-lp.*mp;
t8 = lb.^2;
t9 = mb.*t8;
t10 = lp.^2;
t11 = mp.*t10;
t12 = t9+t11;
M = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,JM33+JP33+t2.^2.*t12+R1.^2.*(mM+mb+mp)+R1.*t2.*cos(t3).*(lb.*mb.*2.0-lp.*mp.*2.0),-R1.*t4.*t5.*t7,0.0,0.0,-R1.*t4.*t5.*t7,t12],[4,4]);
