function HM = mphi_1_ham_m(t,in2,in3,in4)
%MPHI_1_HAM_M
%    HM = MPHI_1_HAM_M(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:28

JP33 = in3(18,:);
dphi = in2(3,:);
dtheta1 = in2(4,:);
g = in3(5,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(1,:);
theta1 = in2(2,:);
HM = [JP33.*dphi.^2.*(1.0./2.0)+kt.*phi.^2.*(1.0./2.0);dtheta1.^2.*(lb.^2.*mb.*(1.0./2.0)+lp.^2.*mp.*(1.0./2.0))+g.*cos(theta1).*(lb.*mb-lp.*mp)];
