function H = mphi_2_ham(t,in2,in3,in4)
%MPHI_2_HAM
%    H = MPHI_2_HAM(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:48

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
R2 = in4(2,:);
dphi = in2(4,:);
dtheta1 = in2(5,:);
dtheta2 = in2(6,:);
g = in3(5,:);
gamma1 = in4(3,:);
gamma2 = in4(4,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(1,:);
psi1 = in4(5,:);
psi2 = in4(6,:);
theta1 = in2(2,:);
theta2 = in2(3,:);
t2 = dphi.^2;
t3 = cos(gamma1);
t4 = R1.^2;
t5 = sin(gamma1);
t6 = cos(gamma2);
t7 = R2.^2;
t8 = sin(gamma2);
t9 = sin(theta1);
t10 = sin(theta2);
t11 = sin(psi1);
t12 = cos(psi1);
t13 = cos(theta1);
t14 = sin(psi2);
t15 = cos(psi2);
t16 = cos(theta2);
t17 = lb.*mb;
t18 = t17-lp.*mp;
H = (lb.^2.*mb+lp.^2.*mp).*(t2.*t9.^2+t2.*t10.^2+dtheta1.^2+dtheta2.^2).*(1.0./2.0)+t2.*(JM33.*2.0+JP33).*(1.0./2.0)+(t2.*(t3.^2.*t4+t4.*t5.^2)+t2.*(t6.^2.*t7+t7.*t8.^2)).*(mM+mb+mp).*(1.0./2.0)+t18.*(R1.*t2.*t3.*t9.*t12.*2.0+R1.*t2.*t5.*t9.*t11.*2.0+R2.*t2.*t6.*t10.*t15.*2.0+R2.*t2.*t8.*t10.*t14.*2.0+R1.*dphi.*dtheta1.*t3.*t11.*t13.*2.0-R1.*dphi.*dtheta1.*t5.*t12.*t13.*2.0+R2.*dphi.*dtheta2.*t6.*t14.*t16.*2.0-R2.*dphi.*dtheta2.*t8.*t15.*t16.*2.0).*(1.0./2.0)+kt.*phi.^2.*(1.0./2.0)+g.*t18.*(t13+t16);
