function M = mphi_3_mass(t,in2,in3,in4)
%MPHI_3_MASS
%    M = MPHI_3_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 14:00:09

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
R2 = in4(2,:);
R3 = in4(3,:);
gamma1 = in4(4,:);
gamma2 = in4(5,:);
gamma3 = in4(6,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(7,:);
psi2 = in4(8,:);
psi3 = in4(9,:);
theta1 = in2(2,:);
theta2 = in2(3,:);
theta3 = in2(4,:);
t2 = sin(theta1);
t3 = sin(theta2);
t4 = lb.^2;
t5 = mb.*t4;
t6 = lp.^2;
t7 = mp.*t6;
t8 = t5+t7;
t9 = sin(theta3);
t10 = mM+mb+mp;
t11 = lb.*mb.*2.0;
t13 = lp.*mp.*2.0;
t12 = t11-t13;
t14 = gamma1-psi1;
t15 = gamma2-psi2;
t16 = lb.*mb;
t19 = lp.*mp;
t17 = t16-t19;
t18 = gamma3-psi3;
t20 = sin(t14);
t21 = cos(theta1);
t22 = sin(t15);
t23 = cos(theta2);
t24 = sin(t18);
t25 = cos(theta3);
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,JM33.*3.0+JP33+R1.^2.*t10+R2.^2.*t10+R3.^2.*t10+t2.^2.*t8+t3.^2.*t8+t8.*t9.^2+R1.*t2.*t12.*cos(t14)+R2.*t3.*t12.*cos(t15)+R3.*t9.*t12.*cos(t18),-R1.*t17.*t20.*t21,-R2.*t17.*t22.*t23,-R3.*t17.*t24.*t25,0.0,0.0,0.0,0.0,-R1.*t17.*t20.*t21,t8,0.0,0.0,0.0,0.0,0.0,0.0,-R2.*t17.*t22.*t23,0.0,t8,0.0,0.0,0.0,0.0,0.0,-R3.*t17.*t24.*t25,0.0,0.0,t8],[8,8]);
