function M = mx_1_mass(t,in2,in3,in4)
%MX_1_MASS
%    M = MX_1_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:37

lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(3,:);
theta1 = in2(2,:);
t2 = cos(psi1);
t3 = cos(theta1);
t4 = lb.*mb;
t5 = t4-lp.*mp;
t6 = t2.*t3.*t5;
M = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,mM+mP+mb+mp,t6,0.0,0.0,t6,lb.^2.*mb+lp.^2.*mp],[4,4]);
