function M = mxphi_2_mass(t,in2,in3,in4)
%MXPHI_2_MASS
%    M = MXPHI_2_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:52

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
R2 = in4(2,:);
gamma1 = in4(3,:);
gamma2 = in4(4,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(2,:);
psi1 = in4(5,:);
psi2 = in4(6,:);
theta1 = in2(3,:);
theta2 = in2(4,:);
t2 = mM+mb+mp;
t3 = lb.*mb;
t6 = lp.*mp;
t4 = t3-t6;
t5 = phi+psi1;
t7 = phi+psi2;
t8 = gamma1+phi;
t9 = sin(t8);
t10 = gamma2+phi;
t11 = sin(t10);
t12 = sin(t5);
t13 = sin(theta1);
t14 = sin(t7);
t15 = sin(theta2);
t16 = -R1.*t2.*t9-R2.*t2.*t11-t4.*t12.*t13-t4.*t14.*t15;
t17 = lb.^2;
t18 = mb.*t17;
t19 = lp.^2;
t20 = mp.*t19;
t21 = t18+t20;
t22 = lb.*mb.*2.0;
t23 = t22-lp.*mp.*2.0;
t24 = gamma1-psi1;
t25 = cos(theta1);
t26 = gamma2-psi2;
t27 = cos(theta2);
t28 = cos(t5);
t29 = t4.*t25.*t28;
t30 = sin(t24);
t31 = cos(t7);
t32 = t4.*t27.*t31;
t33 = sin(t26);
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,mM.*2.0+mP+mb.*2.0+mp.*2.0,t16,t29,t32,0.0,0.0,0.0,0.0,t16,JM33.*2.0+JP33+R1.^2.*t2+R2.^2.*t2+t13.^2.*t21+t15.^2.*t21+R1.*t13.*t23.*cos(t24)+R2.*t15.*t23.*cos(t26),-R1.*t4.*t25.*t30,-R2.*t4.*t27.*t33,0.0,0.0,0.0,0.0,t29,-R1.*t4.*t25.*t30,t21,0.0,0.0,0.0,0.0,0.0,t32,-R2.*t4.*t27.*t33,0.0,t21],[8,8]);
