function dxdt = mxy_1_row(t,in2,in3,in4,in5)
%MXY_1_ROW
%    DXDT = MXY_1_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:30

Utheta1 = in5(3,:);
Ux = in5(1,:);
Uy = in5(2,:);
c = in3(12,:);
d = in3(6,:);
dtheta1 = in2(6,:);
dx = in2(4,:);
dy = in2(5,:);
g = in3(5,:);
k = in3(9,:);
lb = in3(4,:);
lp = in3(3,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(3,:);
theta1 = in2(3,:);
x = in2(1,:);
y = in2(2,:);
t2 = dtheta1.^2;
t3 = sin(theta1);
t4 = lb.*mb;
t6 = lp.*mp;
t5 = t4-t6;
dxdt = [dx;dy;dtheta1;Ux-c.*dx-k.*x+t2.*t3.*t5.*cos(psi1);Uy-c.*dy-k.*y+t2.*t3.*t5.*sin(psi1);Utheta1-d.*dtheta1+g.*t3.*t5];
