function M = mxy_2_mass(t,in2,in3,in4)
%MXY_2_MASS
%    M = MXY_2_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:49

lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(5,:);
psi2 = in4(6,:);
theta1 = in2(3,:);
theta2 = in2(4,:);
t2 = lb.*mb;
t9 = lp.*mp;
t3 = t2-t9;
t4 = mM.*2.0;
t5 = mb.*2.0;
t6 = mp.*2.0;
t7 = mP+t4+t5+t6;
t8 = cos(theta1);
t10 = cos(theta2);
t11 = cos(psi1);
t12 = t3.*t8.*t11;
t13 = sin(psi1);
t14 = t3.*t8.*t13;
t15 = cos(psi2);
t16 = t3.*t10.*t15;
t17 = sin(psi2);
t18 = t3.*t10.*t17;
t19 = lb.^2;
t20 = mb.*t19;
t21 = lp.^2;
t22 = mp.*t21;
t23 = t20+t22;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,t7,0.0,t12,t16,0.0,0.0,0.0,0.0,0.0,t7,t14,t18,0.0,0.0,0.0,0.0,t12,t14,t23,0.0,0.0,0.0,0.0,0.0,t16,t18,0.0,t23],[8,8]);
