function H = mxy_2_ham(t,in2,in3,in4)
%MXY_2_HAM
%    H = MXY_2_HAM(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:51

dtheta1 = in2(7,:);
dtheta2 = in2(8,:);
dx = in2(5,:);
dy = in2(6,:);
g = in3(5,:);
k = in3(9,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(5,:);
psi2 = in4(6,:);
theta1 = in2(3,:);
theta2 = in2(4,:);
x = in2(1,:);
y = in2(2,:);
t2 = cos(theta1);
t3 = cos(theta2);
t4 = lb.*mb;
t5 = t4-lp.*mp;
H = t5.*(dtheta1.*dx.*t2.*cos(psi1).*2.0+dtheta2.*dx.*t3.*cos(psi2).*2.0+dtheta1.*dy.*t2.*sin(psi1).*2.0+dtheta2.*dy.*t3.*sin(psi2).*2.0).*(1.0./2.0)+(dx.^2+dy.^2).*(mM.*2.0+mP+mb.*2.0+mp.*2.0).*(1.0./2.0)+(lb.^2.*mb+lp.^2.*mp).*(dtheta1.^2+dtheta2.^2).*(1.0./2.0)+k.*(x.^2+y.^2).*(1.0./2.0)+g.*t5.*(t2+t3);
