function u = mxyphi_8_esc_or(t,in2,in3,in4)
%MXYPHI_8_ESC_OR
%    U = MXYPHI_8_ESC_OR(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Sep-2018 09:53:17

dtheta1 = in2(15,:);
dtheta2 = in2(16,:);
dtheta3 = in2(17,:);
dtheta4 = in2(18,:);
dtheta5 = in2(19,:);
dtheta6 = in2(20,:);
dtheta7 = in2(21,:);
dtheta8 = in2(22,:);
epsilon = in3(14,:);
tau = in3(15,:);
theta1 = in2(4,:);
theta2 = in2(5,:);
theta3 = in2(6,:);
theta4 = in2(7,:);
theta5 = in2(8,:);
theta6 = in2(9,:);
theta7 = in2(10,:);
theta8 = in2(11,:);
theta_e = in3(16,:);
theta_s = in3(17,:);
t2 = 1.0./epsilon;
t3 = dtheta1.*t2;
t4 = tanh(t3);
t5 = dtheta2.*t2;
t6 = tanh(t5);
t7 = dtheta3.*t2;
t8 = tanh(t7);
t9 = dtheta4.*t2;
t10 = tanh(t9);
t11 = dtheta5.*t2;
t12 = tanh(t11);
t13 = dtheta6.*t2;
t14 = tanh(t13);
t15 = dtheta7.*t2;
t16 = tanh(t15);
t17 = dtheta8.*t2;
t18 = tanh(t17);
u = [0.0;0.0;0.0;t4.*tau.*(tanh(t2.*(theta_e-t4.*theta1))-tanh(t2.*(theta_s-t4.*theta1))).*(1.0./2.0);t6.*tau.*(tanh(t2.*(theta_e-t6.*theta2))-tanh(t2.*(theta_s-t6.*theta2))).*(1.0./2.0);t8.*tau.*(tanh(t2.*(theta_e-t8.*theta3))-tanh(t2.*(theta_s-t8.*theta3))).*(1.0./2.0);t10.*tau.*(tanh(t2.*(theta_e-t10.*theta4))-tanh(t2.*(theta_s-t10.*theta4))).*(1.0./2.0);t12.*tau.*(tanh(t2.*(theta_e-t12.*theta5))-tanh(t2.*(theta_s-t12.*theta5))).*(1.0./2.0);t14.*tau.*(tanh(t2.*(theta_e-t14.*theta6))-tanh(t2.*(theta_s-t14.*theta6))).*(1.0./2.0);t16.*tau.*(tanh(t2.*(theta_e-t16.*theta7))-tanh(t2.*(theta_s-t16.*theta7))).*(1.0./2.0);t18.*tau.*(tanh(t2.*(theta_e-t18.*theta8))-tanh(t2.*(theta_s-t18.*theta8))).*(1.0./2.0)];
