function dxdt = mxyphi_1_row(t,in2,in3,in4,in5)
%MXYPHI_1_ROW
%    DXDT = MXYPHI_1_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Sep-2018 09:48:35

R1 = in4(1,:);
Uphi = in5(3,:);
Utheta1 = in5(4,:);
Ux = in5(1,:);
Uy = in5(2,:);
c = in3(12,:);
ct = in3(13,:);
d = in3(6,:);
dphi = in2(7,:);
dtheta1 = in2(8,:);
dx = in2(5,:);
dy = in2(6,:);
g = in3(5,:);
gamma1 = in4(2,:);
k = in3(9,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(3,:);
psi1 = in4(3,:);
theta1 = in2(4,:);
x = in2(1,:);
y = in2(2,:);
t2 = phi+psi1;
t3 = cos(t2);
t4 = sin(theta1);
t5 = dphi.^2;
t6 = lb.*mb;
t14 = lp.*mp;
t7 = t6-t14;
t8 = sin(t2);
t9 = dtheta1.^2;
t10 = cos(theta1);
t11 = gamma1+phi;
t12 = mM+mb+mp;
t13 = gamma1-psi1;
t15 = lb.^2;
t16 = lp.^2;
t17 = cos(t13);
dxdt = [dx;dy;dphi;dtheta1;Ux-c.*dx-k.*x+t7.*(t3.*t4.*t5+t3.*t4.*t9+dphi.*dtheta1.*t8.*t10.*2.0)+R1.*t5.*t12.*cos(t11);Uy-c.*dy-k.*y+t7.*(t4.*t5.*t8+t4.*t8.*t9-dphi.*dtheta1.*t3.*t10.*2.0)+R1.*t5.*t12.*sin(t11);Uphi-t7.*(R1.*t4.*t9.*sin(t13)+R1.*dphi.*dtheta1.*t10.*t17.*2.0)-ct.*dphi-kt.*phi-dphi.*dtheta1.*t4.*t10.*(mb.*t15.*2.0+mp.*t16.*2.0);Utheta1-d.*dtheta1+g.*t4.*t7+t4.*t5.*t10.*(mb.*t15+mp.*t16)+R1.*t5.*t7.*t10.*t17];
