function u = mxyphi_4_esc_or(t,in2,in3,in4)
%MXYPHI_4_ESC_OR
%    U = MXYPHI_4_ESC_OR(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Sep-2018 09:50:21

dtheta1 = in2(11,:);
dtheta2 = in2(12,:);
dtheta3 = in2(13,:);
dtheta4 = in2(14,:);
epsilon = in3(14,:);
tau = in3(15,:);
theta1 = in2(4,:);
theta2 = in2(5,:);
theta3 = in2(6,:);
theta4 = in2(7,:);
theta_e = in3(16,:);
theta_s = in3(17,:);
t2 = 1.0./epsilon;
t3 = dtheta1.*t2;
t4 = tanh(t3);
t5 = dtheta2.*t2;
t6 = tanh(t5);
t7 = dtheta3.*t2;
t8 = tanh(t7);
t9 = dtheta4.*t2;
t10 = tanh(t9);
u = [0.0;0.0;0.0;t4.*tau.*(tanh(t2.*(theta_e-t4.*theta1))-tanh(t2.*(theta_s-t4.*theta1))).*(1.0./2.0);t6.*tau.*(tanh(t2.*(theta_e-t6.*theta2))-tanh(t2.*(theta_s-t6.*theta2))).*(1.0./2.0);t8.*tau.*(tanh(t2.*(theta_e-t8.*theta3))-tanh(t2.*(theta_s-t8.*theta3))).*(1.0./2.0);t10.*tau.*(tanh(t2.*(theta_e-t10.*theta4))-tanh(t2.*(theta_s-t10.*theta4))).*(1.0./2.0)];
