function H = mxyphi_1_ham(t,in2,in3,in4)
%MXYPHI_1_HAM
%    H = MXYPHI_1_HAM(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    24-Sep-2018 09:48:36

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
dphi = in2(7,:);
dtheta1 = in2(8,:);
dx = in2(5,:);
dy = in2(6,:);
g = in3(5,:);
gamma1 = in4(2,:);
k = in3(9,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(3,:);
psi1 = in4(3,:);
theta1 = in2(4,:);
x = in2(1,:);
y = in2(2,:);
t2 = phi+psi1;
t3 = cos(t2);
t4 = cos(theta1);
t5 = sin(t2);
t6 = sin(theta1);
t7 = dphi.^2;
t8 = cos(gamma1);
t9 = sin(psi1);
t10 = cos(psi1);
t11 = sin(gamma1);
t12 = R1.^2;
t13 = cos(phi);
t14 = sin(phi);
t15 = lb.*mb;
t16 = t15-lp.*mp;
H = t16.*(dphi.*dx.*t5.*t6.*-2.0+dphi.*dy.*t3.*t6.*2.0+dtheta1.*dx.*t3.*t4.*2.0+dtheta1.*dy.*t4.*t5.*2.0+R1.*t6.*t7.*t8.*t10.*2.0+R1.*t6.*t7.*t9.*t11.*2.0+R1.*dphi.*dtheta1.*t4.*t8.*t9.*2.0-R1.*dphi.*dtheta1.*t4.*t10.*t11.*2.0).*(1.0./2.0)+(dx.^2+dy.^2).*(mM+mP+mb+mp).*(1.0./2.0)+(t7.*(t8.^2.*t12+t11.^2.*t12)-dphi.*dx.*(R1.*t8.*t14+R1.*t11.*t13).*2.0+dphi.*dy.*(R1.*t8.*t13-R1.*t11.*t14).*2.0).*(mM+mb+mp).*(1.0./2.0)+kt.*phi.^2.*(1.0./2.0)+(lb.^2.*mb+lp.^2.*mp).*(t6.^2.*t7+dtheta1.^2).*(1.0./2.0)+t7.*(JM33+JP33).*(1.0./2.0)+k.*(x.^2+y.^2).*(1.0./2.0)+g.*t4.*t16;
