function H = my_1_ham(t,in2,in3,in4)
%MY_1_HAM
%    H = MY_1_HAM(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:41

dtheta1 = in2(4,:);
dy = in2(3,:);
g = in3(5,:);
k = in3(9,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(3,:);
theta1 = in2(2,:);
y = in2(1,:);
t2 = cos(theta1);
t3 = lb.*mb;
t4 = t3-lp.*mp;
H = dy.^2.*(mM+mP+mb+mp).*(1.0./2.0)+k.*y.^2.*(1.0./2.0)+dtheta1.^2.*(lb.^2.*mb+lp.^2.*mp).*(1.0./2.0)+g.*t2.*t4+dtheta1.*dy.*t2.*t4.*sin(psi1);
