function dxdt = my_3_row(t,in2,in3,in4,in5)
%MY_3_ROW
%    DXDT = MY_3_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 14:00:28

Utheta1 = in5(2,:);
Utheta2 = in5(3,:);
Utheta3 = in5(4,:);
Uy = in5(1,:);
c = in3(12,:);
d = in3(6,:);
dtheta1 = in2(6,:);
dtheta2 = in2(7,:);
dtheta3 = in2(8,:);
dy = in2(5,:);
g = in3(5,:);
k = in3(9,:);
lb = in3(4,:);
lp = in3(3,:);
mb = in3(2,:);
mp = in3(1,:);
psi1 = in4(7,:);
psi2 = in4(8,:);
psi3 = in4(9,:);
theta1 = in2(2,:);
theta2 = in2(3,:);
theta3 = in2(4,:);
y = in2(1,:);
t2 = sin(theta1);
t3 = lb.*mb;
t6 = lp.*mp;
t4 = t3-t6;
t5 = sin(theta2);
t7 = sin(theta3);
dxdt = [dy;dtheta1;dtheta2;dtheta3;Uy-c.*dy-k.*y+t4.*(dtheta1.^2.*t2.*sin(psi1)+dtheta2.^2.*t5.*sin(psi2)+dtheta3.^2.*t7.*sin(psi3));Utheta1-d.*dtheta1+g.*t2.*t4;Utheta2-d.*dtheta2+g.*t4.*t5;Utheta3-d.*dtheta3+g.*t4.*t7];
