function dxdt = myphi_1_row(t,in2,in3,in4,in5)
%MYPHI_1_ROW
%    DXDT = MYPHI_1_ROW(T,IN2,IN3,IN4,IN5)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:35

R1 = in4(1,:);
Uphi = in5(2,:);
Utheta1 = in5(3,:);
Uy = in5(1,:);
c = in3(12,:);
ct = in3(13,:);
d = in3(6,:);
dphi = in2(5,:);
dtheta1 = in2(6,:);
dy = in2(4,:);
g = in3(5,:);
gamma1 = in4(2,:);
k = in3(9,:);
kt = in3(10,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(2,:);
psi1 = in4(3,:);
theta1 = in2(3,:);
y = in2(1,:);
t2 = phi+psi1;
t3 = sin(t2);
t4 = sin(theta1);
t5 = dphi.^2;
t6 = dtheta1.^2;
t7 = cos(theta1);
t8 = gamma1-psi1;
t9 = lb.*mb;
t11 = lp.*mp;
t10 = t9-t11;
t12 = lb.^2;
t13 = lp.^2;
t14 = cos(t8);
dxdt = [dy;dphi;dtheta1;Uy+t10.*(t3.*t4.*t5+t3.*t4.*t6-dphi.*dtheta1.*t7.*cos(t2).*2.0)-c.*dy-k.*y+R1.*t5.*sin(gamma1+phi).*(mM+mb+mp);Uphi-t10.*(R1.*t4.*t6.*sin(t8)+R1.*dphi.*dtheta1.*t7.*t14.*2.0)-ct.*dphi-kt.*phi-dphi.*dtheta1.*t4.*t7.*(mb.*t12.*2.0+mp.*t13.*2.0);Utheta1-d.*dtheta1+g.*t4.*t10+t4.*t5.*t7.*(mb.*t12+mp.*t13)+R1.*t5.*t7.*t10.*t14];
