function M = myphi_1_mass(t,in2,in3,in4)
%MYPHI_1_MASS
%    M = MYPHI_1_MASS(T,IN2,IN3,IN4)

%    This function was generated by the Symbolic Math Toolbox version 8.1.
%    09-Aug-2018 13:59:34

JM33 = in3(19,:);
JP33 = in3(18,:);
R1 = in4(1,:);
gamma1 = in4(2,:);
lb = in3(4,:);
lp = in3(3,:);
mM = in3(8,:);
mP = in3(7,:);
mb = in3(2,:);
mp = in3(1,:);
phi = in2(2,:);
psi1 = in4(3,:);
theta1 = in2(3,:);
t2 = phi+psi1;
t3 = lb.*mb;
t7 = lp.*mp;
t4 = t3-t7;
t5 = cos(t2);
t6 = sin(theta1);
t8 = t4.*t5.*t6;
t9 = gamma1+phi;
t10 = cos(t9);
t11 = mM+mb+mp;
t12 = R1.*t10.*t11;
t13 = t8+t12;
t14 = gamma1-psi1;
t15 = cos(theta1);
t16 = sin(t2);
t17 = t4.*t15.*t16;
t18 = sin(t14);
t19 = lb.^2;
t20 = mb.*t19;
t21 = lp.^2;
t22 = mp.*t21;
t23 = t20+t22;
M = reshape([1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,mM+mP+mb+mp,t13,t17,0.0,0.0,0.0,t13,JM33+JP33+R1.^2.*t11+t6.^2.*t23+R1.*t6.*cos(t14).*(lb.*mb.*2.0-lp.*mp.*2.0),-R1.*t4.*t15.*t18,0.0,0.0,0.0,t17,-R1.*t4.*t15.*t18,t23],[6,6]);
